export const ADD_TO_CART_ITEM = 'ADD_TO_CART_ITEM'
export const REMOVE_FROM_CART_ITEM = 'REMOVE_FROM_CART_ITEM'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'
export const RESET_CART_AFTER_ORDER_PLACEMENT = 'RESET_CART_AFTER_ORDER_PLACEMENT'