export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET'

export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'

export const ORDERS_LIST_MY_SUCCESS = 'ORDERS_LIST_MY_SUCCESS'
export const ORDERS_LIST_MY_FAIL = 'ORDERS_LIST_MY_FAIL'
export const ORDERS_LIST_MY_RESET = 'ORDERS_LIST_MY_RESET'

export const GET_ALL_ORDERS_BY_ADMIN_SUCCESS = 'GET_ALL_ORDERS_BY_ADMIN_SUCCESS'
export const GET_ALL_ORDERS_BY_ADMIN_FAIL = 'GET_ALL_ORDERS_BY_ADMIN_FAIL'

export const DELETE_ORDER_BY_ADMIN_SUCCESS = 'DELETE_ORDER_BY_ADMIN_SUCCESS'
export const DELETE_ORDER_BY_ADMIN_FAIL = 'DELETE_ORDER_BY_ADMIN_FAIL'