export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST'
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS'
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL'

export const NEW_ARRIVED_PRODUCTS_SUCCESS = 'NEW_ARRIVED_PRODUCTS_SUCCESS'
export const NEW_ARRIVED_PRODUCTS_FAIL = 'NEW_ARRIVED_PRODUCTS_FAIL'

export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'
export const PRODUCT_DETAILS_RESET = 'PRODUCT_DETAILS_RESET'

export const USER_PRODUCTS_SUCCESS = 'USER_PRODUCTS_SUCCESS'
export const USER_PRODUCTS_FAIL = 'USER_PRODUCTS_FAIL'
export const USER_PRODUCTS_RESET = 'USER_PRODUCTS_RESET'

export const USER_PRODUCT_DELETE_REQUEST = 'USER_PRODUCT_DELETE_REQUEST'
export const USER_PRODUCT_DELETE_SUCCESS = 'USER_PRODUCT_DELETE_SUCCESS'
export const USER_PRODUCT_DELETE_FAIL = 'USER_PRODUCT_DELETE_FAIL'

export const CREATE_NEW_PRODUCT_REQUEST = 'CREATE_NEW_PRODUCT_REQUEST'
export const CREATE_NEW_PRODUCT_SUCCESS = 'CREATE_NEW_PRODUCT_SUCCESS'
export const CREATE_NEW_PRODUCT_FAIL = 'CREATE_NEW_PRODUCT_FAIL'
export const CREATE_NEW_PRODUCT_RESET = 'CREATE_NEW_PRODUCT_RESET'

export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL'

export const USERS_PRODUCTS_BY_ADMIN_SUCCESS = 'USERS_PRODUCTS_BY_ADMIN_SUCCESS'
export const USERS_PRODUCTS_BY_ADMIN_FAIL = 'USERS_PRODUCTS_BY_ADMIN_FAIL'
export const USERS_PRODUCTS_BY_ADMIN_RESET = 'USERS_PRODUCTS_BY_ADMIN_RESET'

export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES'